[build-system]
requires = [
    "setuptools>=68.0.0",
    "wheel>=0.42.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "daf_gqlquery"
dynamic = ["version"]
authors = [
    { name = "Peter Segerstedt" },
]
description = "Code for the pesd.daf-query.DafGQLQuery transformer in FME"
readme = "README.md"
keywords = ["fme", "fmepy", "package"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: FME",
    "Private :: Do Not Upload",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "vendorize>=0.3.0",
    "pytest>=7.4.4",
    "black>=23.3.0",
]

[tool.setuptools.dynamic]
version = { attr = "daf_gqlquery.__version__" }

[tool.setuptools.packages.find]
where = ["src"]
